### ISSUE TITLE
auto_referee  can not be used

### ISSUE THREAD

**Issue by HubFire** [nubot-nudt/simatch#6]
When  I run ` rosrun auto_referee auto_referee -1`，i got problem :
[ERROR] [1487833817.536093395, 2205.285000000]: Client [/rival_world_model4] wants topic /rival/receive_from_coach to have datatype/md5sum [nubot_common/CoachInfo/7bb01a0f4328cb28beb61d4f502c2969], but our version has [nubot_common/CoachInfo/1d1d66a902b8fe8ac284f51c0af16e45]. Dropping connection.

And no instructions to both teams。
Should  I  run  coach ,and  the  auto_referee  send  comand to both  coach ,Both coaches give instructions to the team？

**Comment by nubot-nudt** [comment]
1. The problem is similar to [link][1]. Please make sure you run all the packages in simatch only. It is recommended that you put simatch into an isolated workspace. Everytime you want to use simatch, you should source this workspace so that you won't run other packages outside of this workspace accidentally.
2. If you run auto_referee, it is not necessary to run Coach, which is quite different from the real RoboCup MSL competition. auto_referee can send all game commands to robots directly. However, you could still run coach to observe the robot states and other information for code debugging or strategy improvement and etc. 

[1]: https://github.com/nubot-nudt/coach4sim/issues/1

**Comment by HubFire** [comment]
On  computer A， I run   `roslaunch nubot_gazebo game_ready.launch` and   `rosrun auto_referee auto_referee -1`,  which are all  in simatch directory ,and I run  `source devel/setup.bash`  every time in a new terminal .
On  computer B and C  ,I run`  ./src/cyan_spawn_model.sh ` and `./src/magenta_spawn_model.sh` ,which are all in  nubot_ws.

**Comment by HubFire** [comment]
Do you mean that  I should run robot_code  in simatch instead of  nubot_ws?

**Comment by nubot-nudt** [comment]
Yes, you should run robot_code in simatch instead of nubot_ws.
